### ISSUE TITLE
An error occurred while processing your request.

### ISSUE THREAD

**Issue by Fank** [TorchAPI/Website#15]
When trying to upload a new plugin version i get the following error:
```
Error.
An error occurred while processing your request.
Request ID: 0HLL11P5Q2P7Q:00000001

Development Mode
Swapping to Development environment will display more detailed information about the error that occurred.

Development environment should not be enabled in deployed applications, as it can result in sensitive information from exceptions being displayed to end users. For local debugging, development environment can be enabled by setting the ASPNETCORE_ENVIRONMENT environment variable to Development, and restarting the application.
```

And yes i validated that the plugin "id" and "name" matches

Plugin https://torchapi.net/plugins/item/3cd3ba7f-c47c-4efe-8cf1-bd3f618f5b9c
New version:
[SEDiscordBridge.zip](https://github.com/TorchAPI/Website/files/2943681/SEDiscordBridge.zip)

**Comment by Fank** [comment]
I deleted 1.5.2 and tried to reupload the 1.5.2 version, same error

**Comment by biscuitWizard** [comment]
Cannot upload any file by hand. If the plugin exceeds 1.2MB, you will instead get a 413.

**Comment by Jimmacle** [comment]
Fixed, limit upped to 8MB.
