### ISSUE TITLE
Registering as new user, capcha is broken.

### ISSUE THREAD

**Issue by mmetully** [TorchAPI/Website#17]
Registration page:
![image](https://user-images.githubusercontent.com/3114412/64884919-aefe3d00-d617-11e9-8374-b8e405c10ba1.png)

Developer console:
![image](https://user-images.githubusercontent.com/3114412/64884890-a0178a80-d617-11e9-98a7-ca6c58ae9d33.png)

**Comment by Jimmacle** [comment]
I forgot that I had some WIP changes on this branch, I'll revert them.

**Comment by Jimmacle** [comment]
Fix is live
